language: objective-c
before_install:
- export LANG=en_US.UTF-8
- echo "Install lizard for cyclomatic complexity analysis"
- pip install --no-use-wheel lizard
- echo "Update fastlane"
- gem update fastlane
- echo "Install oclint for code quality analysis"
- brew cask uninstall --force oclint
- brew tap oclint/formulae
- brew install oclint
script:
- lizard -C 5 -w -i 0 cicd
- bash ./fastlane/travis.sh
- xcodebuild | tee xcodebuild.log
- oclint-xcodebuild
- oclint-json-compilation-database
after_success:
- true
after_script:
- true